server:
  error:
    include-message: always
  port: 8191
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
    timeouts:
      connect-timeout: 2000
      read-timeout: 10000
      write-timeout: 2000
#  recommendation-service:
#    url: http://localhost:8155/recommendation
#    timeouts:
#      connect-timeout: 2000
#      read-timeout: 10000
#      write-timeout: 2000
