server:
  error:
    include-message: always
  port: 8191
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
#  recommendation-service:
#    url: http://localhost:8155/recommendation